server:
  port: 8085

spring:
  application:
    name: dash-config
  profiles:
    # 使用本地配置文件
    active: native
  cloud:
    config:
      server:
        # 本地配置文件位置，使用此配置项，还需要启用spring.profiles.active=native
        native:
          search-locations: C:/study/dashcloud-config-files
        # git配置文件仓库配置
#        git:
#          uri: https://example.com/my/repo
#          skipSslValidation: true


eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8767/eureka/