server:
  port: 8080

spring:
  application:
    name: dash-gateway

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8767/eureka/

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  semaphore:
    max-semaphores: 500
  routes:
    dash-system:
      path: /api-system/**
      serviceId: dash-modules-system
    dash-config:
      path: /dash-config/**
      serviceId: dash-config