server:
  port: 8080

spring:
  application:
    name: dash-gateway
  profiles:
    active: dev
  config:
    import: optional:configserver:dash-config
  cloud:
    config:
      uri:
        - "http://localhost:8085"
      profile: dev
      discovery:
        # 启用 eureka配置发现
        enabled: true
        # 配置服务的serviceId
        serviceId: dash-config
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8767/eureka/

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  semaphore:
    max-semaphores: 500
  routes:
    dash-system:
      path: /api-system/**
      serviceId: dash-modules-system
    dash-config:
      path: /dash-config/**
      serviceId: dash-config
    dash-auth:
      path: /dash-auth/**
      serviceId: dash-auth

# 不校验白名单
#ignore:
#  whites:
#    - "/dash-auth/login"
